import Metrics from './field.metrics';

const {X: FIELD_X, Y: FIELD_Y} = Metrics;
export const IMAGE_W = 70;
export const IMAGE_H = IMAGE_W;

export const X = FIELD_X + 50;
export const Y = FIELD_Y - 5;

export const  STROKE_WIDTH = 1;

export const PLAYER_SPACE = 60;

export const PLAYER_NAME_SPACE = 25;
export const PLAYER_NAME_SEPARATION = 5;

export const ROW_SEPARATION = 10;

export const CARD_STYLE_NAME_SPACE = 50;
export const CARD_STYLE_NUMBER_SPACE = 20;
export const CARD_STYLE_CARD_RADIUS = 5;
export const CARD_STYLE_OPACITY = 0.75;

export const CONTAINER_SPACE = 5;

export const CARD_STYLE = {
	IMAGE:IMAGE_W,
	NAME_SPACE: CARD_STYLE_NAME_SPACE,
	NUMBER_SPACE: CARD_STYLE_NUMBER_SPACE,
	RADIUS: CARD_STYLE_CARD_RADIUS,
	OPACITY: CARD_STYLE_OPACITY,
	HEIGHT: CARD_STYLE_NUMBER_SPACE,
	WIDTH: IMAGE_W,
	SPACE: STROKE_WIDTH,
	CONTAINER_HEIGHT: IMAGE_W + STROKE_WIDTH + CARD_STYLE_NUMBER_SPACE + CONTAINER_SPACE * 2,
	CONTAINER_WIDTH: IMAGE_W + CONTAINER_SPACE * 2,
	CONTAINER_SPACE,
}
